listenPort: 8080
http:
  - host: "localhost:8080"
    port: 9001
    backend: localhost
    pathPrefix: "/"
  - host: "localhost:8080"
    port: 9002
    backend: localhost
    pathPrefix: "/second" 
  - host: "localhost:8080"
    port: 9003
    backend: localhost
    pathPrefix: "/third" 
