listenPort: 8080
http:
  - host: "localhost:8080"
    port: 9001
    backend: localhost
    path: "/*"
  - host: "localhost:8080"
    port: 9002
    backend: localhost
    path: "/second" 
  - host: "localhost:8080"
    port: 9003
    backend: localhost
    path: "/third" 
