listenPort: 8080
http:
  - host: "rpchost"
    port: 9001
    backend: localhost
    path: ""
  - host: "rpchost"
    port: 9002
    backend: localhost
    path: "" 
  - host: "rpchost"
    port: 9003
    backend: localhost
    path: "" 
